services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gita-backend-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/gitadb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - JWT_SECRET=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - gita-network

  postgres:
    image: postgres:16-alpine
    container_name: gita-postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: gitadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - gita-network

  redis:
    image: redis:7-alpine
    container_name: gita-redis-cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - gita-network

networks:
  gita-network:
    driver: bridge

volumes:
  pgdata:
  redisdata:
