-- Flyway Migration V1: Schema Initialization
-- Compatible with PostgreSQL and H2

CREATE TABLE IF NOT EXISTS chapters (
    chapter_number INT PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    subtitle VARCHAR(200),
    sanskrit_name VARCHAR(150) NOT NULL,
    transliterated VARCHAR(150),
    theme TEXT,
    verse_count INT NOT NULL,
    color VARCHAR(20),
    summary_en TEXT,
    summary_hi TEXT
);

CREATE TABLE IF NOT EXISTS verses (
    id BIGINT PRIMARY KEY,
    chapter_number INT NOT NULL,
    verse_number INT NOT NULL,
    sanskrit TEXT NOT NULL,
    transliteration TEXT,
    word_meanings TEXT,
    CONSTRAINT fk_verse_chapter FOREIGN KEY (chapter_number) REFERENCES chapters(chapter_number) ON DELETE CASCADE,
    CONSTRAINT uk_chapter_verse UNIQUE (chapter_number, verse_number)
);

CREATE TABLE IF NOT EXISTS translations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    verse_id BIGINT NOT NULL,
    language VARCHAR(10) NOT NULL,
    author VARCHAR(100) NOT NULL,
    translation_text TEXT NOT NULL,
    CONSTRAINT fk_trans_verse FOREIGN KEY (verse_id) REFERENCES verses(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS explanations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    verse_id BIGINT NOT NULL,
    language VARCHAR(10) NOT NULL,
    author VARCHAR(100) NOT NULL,
    explanation_text TEXT NOT NULL,
    CONSTRAINT fk_expl_verse FOREIGN KEY (verse_id) REFERENCES verses(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS verse_keywords (
    verse_id BIGINT NOT NULL,
    keyword VARCHAR(100) NOT NULL,
    CONSTRAINT fk_kw_verse FOREIGN KEY (verse_id) REFERENCES verses(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dilemma_categories (
    id BIGINT PRIMARY KEY,
    code VARCHAR(50) UNIQUE NOT NULL,
    title VARCHAR(100) NOT NULL,
    title_hindi VARCHAR(100) NOT NULL,
    description TEXT,
    icon VARCHAR(20),
    prescription TEXT
);

CREATE TABLE IF NOT EXISTS verse_dilemmas (
    dilemma_id BIGINT NOT NULL,
    verse_id BIGINT NOT NULL,
    takeaway TEXT,
    PRIMARY KEY (dilemma_id, verse_id),
    CONSTRAINT fk_vd_dilemma FOREIGN KEY (dilemma_id) REFERENCES dilemma_categories(id) ON DELETE CASCADE,
    CONSTRAINT fk_vd_verse FOREIGN KEY (verse_id) REFERENCES verses(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'ROLE_USER',
    streak_count INT NOT NULL DEFAULT 0,
    last_active_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS journal_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    verse_id BIGINT,
    reflection_text TEXT NOT NULL,
    action_commitment TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    version INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_journal_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_journal_verse FOREIGN KEY (verse_id) REFERENCES verses(id) ON DELETE SET NULL
);

-- Indexes for lightning fast lookups
CREATE INDEX IF NOT EXISTS idx_verse_lookup ON verses(chapter_number, verse_number);
CREATE INDEX IF NOT EXISTS idx_trans_lookup ON translations(verse_id, language);
CREATE INDEX IF NOT EXISTS idx_expl_lookup ON explanations(verse_id, language);
CREATE INDEX IF NOT EXISTS idx_kw_keyword ON verse_keywords(keyword);
CREATE INDEX IF NOT EXISTS idx_journal_user ON journal_entries(user_id, created_at);